version: 2.1

orbs:
  boot: jorjazo/boot@1.1.1
  kube: jorjazo/kubernetes@1.0.0

workflows:
  build-docker:
    jobs:
    - boot/build-test-jar
    - boot/docker-build-push:
        requires:
        - boot/build-test-jar
        context: casa
        buildx: true
        platform: linux/amd64,linux/arm/v7,linux/arm64/v8
        base-image: adoptopenjdk:14-hotspot
    - approve-deploy:
        type: approval
        requires:
        - boot/docker-build-push
    - kube/deploy:
        context: casa
        requires:
        - approve-deploy
        server: ${KUBE_SERVER}
        token: ${KUBE_TOKEN}
        deployment: home-api
        container: home-api
